# Site settings
title: Adam Morgan
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I'm Adam, a developer from Mountain Ash, with over 6 years experience. I design and build beautiful websites that are very user friendly.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://adammorgan.wales" # the base hostname & protocol for your site

# Social Media Accounta
twitter_username:         adamtaffymorgan
github_username:          adamccfc
codepen_username:         AdamCCFC
instagram_username:       adamccfc
stackoverflow_username:   adam-morgan
linkedin_username:        adam-morgan-230a9672

# Use comments
comments: true

# Build settings
markdown: kramdown

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Google Tag Manager
google_tag_manager_id: GTM-NB9NCK
