# Site settings
title: Adam Morgan
email: adam.morgan@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://adammorgan.wales" # the base hostname & protocol for your site
twitter_username: adamtaffymorgan
github_username:  adamccfc

# Build settings
markdown: kramdown
